version: '3.6'
services:
  telegraf:
    image: telegraf:1.29
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '127.0.0.1:8125:8125/udp'
    networks:
      - projector_network

  influxdb:
    image: influxdb:1.8-alpine
    env_file: configuration.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - projector_network

  grafana:
    image: grafana/grafana:8.0.2
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - projector_network

  mongo:
    container_name: mongodb
    image: mongo
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=example
#      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_data:/data/configdb
    restart: always
    networks:
      - projector_network

#  nginx:
#    container_name: nginx
#    image: nginx:1.25.3
#    volumes:
#      #      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      #      - ./gzip.conf:/etc/nginx/conf.d/gzip.conf
#      - ./html:/usr/share/nginx/html:ro
#    ports:
#      - 80:80
##      - '8080:80'
##      - '8081:81'
#    networks:
#      - projector_network

  elastic:
    container_name: elasticsearch
    image: elasticsearch:7.17.16
    environment:
      - ELASTIC_PASSWORD=pleasechangeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - projector_network

volumes:
  grafana_data: {}
  influxdb_data: {}
  mongodb_data: {}
  elastic_data: {}

networks:
  projector_network:
    driver: bridge
